:concurrency: 25
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: #./log/sidekiq.log
:queues:
 - default
 - mailers
:schedule:
  first:
    cron: '0 5 * * 1'   # Every monday of the week at 5AM
    class: 'EWorker'